export type FontSeedEntry = {
  slug: string;
  family: string;
  category: string;
  tags: string[];
  suitableForDisplay: boolean;
  suitableForBody: boolean;
  sortOrder: number;
};

export const fontsV1: FontSeedEntry[] = [
  // Mock / hero fonts
  {
    slug: 'space-grotesk',
    family: 'Space Grotesk',
    category: 'sans-serif',
    tags: ['Modern', 'Tech', 'Confident'],
    suitableForDisplay: true,
    suitableForBody: true,
    sortOrder: 1,
  },
  {
    slug: 'playfair-display',
    family: 'Playfair Display',
    category: 'serif',
    tags: ['Elegant', 'Luxury', 'Editorial'],
    suitableForDisplay: true,
    suitableForBody: false,
    sortOrder: 2,
  },
  {
    slug: 'dm-serif-display',
    family: 'DM Serif Display',
    category: 'serif',
    tags: ['Classic', 'Trustworthy'],
    suitableForDisplay: true,
    suitableForBody: false,
    sortOrder: 3,
  },
  {
    slug: 'bebas-neue',
    family: 'Bebas Neue',
    category: 'display',
    tags: ['Bold', 'Modern', 'Impactful'],
    suitableForDisplay: true,
    suitableForBody: false,
    sortOrder: 4,
  },
  {
    slug: 'poppins',
    family: 'Poppins',
    category: 'sans-serif',
    tags: ['Friendly', 'Clean', 'Versatile'],
    suitableForDisplay: true,
    suitableForBody: true,
    sortOrder: 5,
  },
  {
    slug: 'protest-strike',
    family: 'Protest Strike',
    category: 'display',
    tags: ['Bold', 'Modern', 'Impactful'],
    suitableForDisplay: true,
    suitableForBody: false,
    sortOrder: 6,
  },
  {
    slug: 'barlow',
    family: 'Barlow',
    category: 'sans-serif',
    tags: ['Clean', 'Technical', 'Readable'],
    suitableForDisplay: true,
    suitableForBody: true,
    sortOrder: 7,
  },
  {
    slug: 'inter',
    family: 'Inter',
    category: 'sans-serif',
    tags: ['Clean', 'Readable', 'Neutral'],
    suitableForDisplay: false,
    suitableForBody: true,
    sortOrder: 8,
  },
  {
    slug: 'roboto',
    family: 'Roboto',
    category: 'sans-serif',
    tags: ['Neutral', 'Readable', 'Familiar'],
    suitableForDisplay: false,
    suitableForBody: true,
    sortOrder: 9,
  },
  {
    slug: 'montserrat',
    family: 'Montserrat',
    category: 'sans-serif',
    tags: ['Modern', 'Geometric', 'Brand'],
    suitableForDisplay: true,
    suitableForBody: true,
    sortOrder: 10,
  },

  // Display-focused
  {
    slug: 'oswald',
    family: 'Oswald',
    category: 'sans-serif',
    tags: ['Bold', 'Condensed', 'Impactful'],
    suitableForDisplay: true,
    suitableForBody: false,
    sortOrder: 11,
  },
  {
    slug: 'raleway',
    family: 'Raleway',
    category: 'sans-serif',
    tags: ['Elegant', 'Modern', 'Light'],
    suitableForDisplay: true,
    suitableForBody: true,
    sortOrder: 12,
  },
  {
    slug: 'abril-fatface',
    family: 'Abril Fatface',
    category: 'display',
    tags: ['Dramatic', 'Editorial', 'Luxury'],
    suitableForDisplay: true,
    suitableForBody: false,
    sortOrder: 13,
  },
  {
    slug: 'archivo-black',
    family: 'Archivo Black',
    category: 'sans-serif',
    tags: ['Bold', 'Loud', 'Impactful'],
    suitableForDisplay: true,
    suitableForBody: false,
    sortOrder: 14,
  },
  {
    slug: 'anton',
    family: 'Anton',
    category: 'sans-serif',
    tags: ['Bold', 'Condensed', 'Strong'],
    suitableForDisplay: true,
    suitableForBody: false,
    sortOrder: 15,
  },
  {
    slug: 'bangers',
    family: 'Bangers',
    category: 'display',
    tags: ['Playful', 'Comic', 'Energetic'],
    suitableForDisplay: true,
    suitableForBody: false,
    sortOrder: 16,
  },
  {
    slug: 'bitter',
    family: 'Bitter',
    category: 'serif',
    tags: ['Editorial', 'Strong', 'Readable'],
    suitableForDisplay: true,
    suitableForBody: true,
    sortOrder: 17,
  },
  {
    slug: 'cabin',
    family: 'Cabin',
    category: 'sans-serif',
    tags: ['Warm', 'Humanist', 'Friendly'],
    suitableForDisplay: true,
    suitableForBody: true,
    sortOrder: 18,
  },
  {
    slug: 'cinzel',
    family: 'Cinzel',
    category: 'serif',
    tags: ['Classic', 'Luxury', 'Formal'],
    suitableForDisplay: true,
    suitableForBody: false,
    sortOrder: 19,
  },
  {
    slug: 'comfortaa',
    family: 'Comfortaa',
    category: 'display',
    tags: ['Rounded', 'Friendly', 'Soft'],
    suitableForDisplay: true,
    suitableForBody: false,
    sortOrder: 20,
  },
  {
    slug: 'cormorant-garamond',
    family: 'Cormorant Garamond',
    category: 'serif',
    tags: ['Elegant', 'Literary', 'Refined'],
    suitableForDisplay: true,
    suitableForBody: true,
    sortOrder: 21,
  },
  {
    slug: 'creepster',
    family: 'Creepster',
    category: 'display',
    tags: ['Horror', 'Playful', 'Novelty'],
    suitableForDisplay: true,
    suitableForBody: false,
    sortOrder: 22,
  },
  {
    slug: 'dm-sans',
    family: 'DM Sans',
    category: 'sans-serif',
    tags: ['Modern', 'Geometric', 'Clean'],
    suitableForDisplay: true,
    suitableForBody: true,
    sortOrder: 23,
  },
  {
    slug: 'exo-2',
    family: 'Exo 2',
    category: 'sans-serif',
    tags: ['Tech', 'Futuristic', 'Modern'],
    suitableForDisplay: true,
    suitableForBody: true,
    sortOrder: 24,
  },
  {
    slug: 'fjalla-one',
    family: 'Fjalla One',
    category: 'sans-serif',
    tags: ['Bold', 'Condensed', 'Headline'],
    suitableForDisplay: true,
    suitableForBody: false,
    sortOrder: 25,
  },
  {
    slug: 'fredoka',
    family: 'Fredoka',
    category: 'sans-serif',
    tags: ['Friendly', 'Rounded', 'Playful'],
    suitableForDisplay: true,
    suitableForBody: false,
    sortOrder: 26,
  },
  {
    slug: 'great-vibes',
    family: 'Great Vibes',
    category: 'handwriting',
    tags: ['Script', 'Elegant', 'Romantic'],
    suitableForDisplay: true,
    suitableForBody: false,
    sortOrder: 27,
  },
  {
    slug: 'ibm-plex-sans',
    family: 'IBM Plex Sans',
    category: 'sans-serif',
    tags: ['Corporate', 'Technical', 'Clear'],
    suitableForDisplay: true,
    suitableForBody: true,
    sortOrder: 28,
  },
  {
    slug: 'josefin-sans',
    family: 'Josefin Sans',
    category: 'sans-serif',
    tags: ['Elegant', 'Geometric', 'Stylish'],
    suitableForDisplay: true,
    suitableForBody: false,
    sortOrder: 29,
  },
  {
    slug: 'kanit',
    family: 'Kanit',
    category: 'sans-serif',
    tags: ['Modern', 'Bold', 'Versatile'],
    suitableForDisplay: true,
    suitableForBody: true,
    sortOrder: 30,
  },
  {
    slug: 'lato',
    family: 'Lato',
    category: 'sans-serif',
    tags: ['Friendly', 'Readable', 'Warm'],
    suitableForDisplay: true,
    suitableForBody: true,
    sortOrder: 31,
  },
  {
    slug: 'libre-baskerville',
    family: 'Libre Baskerville',
    category: 'serif',
    tags: ['Classic', 'Editorial', 'Trustworthy'],
    suitableForDisplay: true,
    suitableForBody: true,
    sortOrder: 32,
  },
  {
    slug: 'lobster',
    family: 'Lobster',
    category: 'display',
    tags: ['Script', 'Bold', 'Casual'],
    suitableForDisplay: true,
    suitableForBody: false,
    sortOrder: 33,
  },
  {
    slug: 'manrope',
    family: 'Manrope',
    category: 'sans-serif',
    tags: ['Modern', 'Geometric', 'Clean'],
    suitableForDisplay: true,
    suitableForBody: true,
    sortOrder: 34,
  },
  {
    slug: 'merriweather',
    family: 'Merriweather',
    category: 'serif',
    tags: ['Readable', 'Editorial', 'Classic'],
    suitableForDisplay: false,
    suitableForBody: true,
    sortOrder: 35,
  },
  {
    slug: 'nunito',
    family: 'Nunito',
    category: 'sans-serif',
    tags: ['Rounded', 'Friendly', 'Soft'],
    suitableForDisplay: true,
    suitableForBody: true,
    sortOrder: 36,
  },
  {
    slug: 'outfit',
    family: 'Outfit',
    category: 'sans-serif',
    tags: ['Modern', 'Geometric', 'Brand'],
    suitableForDisplay: true,
    suitableForBody: true,
    sortOrder: 37,
  },
  {
    slug: 'pacifico',
    family: 'Pacifico',
    category: 'handwriting',
    tags: ['Script', 'Casual', 'Fun'],
    suitableForDisplay: true,
    suitableForBody: false,
    sortOrder: 38,
  },
  {
    slug: 'passion-one',
    family: 'Passion One',
    category: 'display',
    tags: ['Bold', 'Impactful', 'Strong'],
    suitableForDisplay: true,
    suitableForBody: false,
    sortOrder: 39,
  },
  {
    slug: 'permanent-marker',
    family: 'Permanent Marker',
    category: 'handwriting',
    tags: ['Marker', 'Casual', 'Handwritten'],
    suitableForDisplay: true,
    suitableForBody: false,
    sortOrder: 40,
  },
  {
    slug: 'pt-sans',
    family: 'PT Sans',
    category: 'sans-serif',
    tags: ['Neutral', 'Readable', 'Clear'],
    suitableForDisplay: false,
    suitableForBody: true,
    sortOrder: 41,
  },
  {
    slug: 'pt-serif',
    family: 'PT Serif',
    category: 'serif',
    tags: ['Classic', 'Readable', 'Editorial'],
    suitableForDisplay: true,
    suitableForBody: true,
    sortOrder: 42,
  },
  {
    slug: 'quicksand',
    family: 'Quicksand',
    category: 'sans-serif',
    tags: ['Rounded', 'Soft', 'Friendly'],
    suitableForDisplay: true,
    suitableForBody: true,
    sortOrder: 43,
  },
  {
    slug: 'righteous',
    family: 'Righteous',
    category: 'display',
    tags: ['Retro', 'Bold', 'Display'],
    suitableForDisplay: true,
    suitableForBody: false,
    sortOrder: 44,
  },
  {
    slug: 'rubik',
    family: 'Rubik',
    category: 'sans-serif',
    tags: ['Rounded', 'Modern', 'Friendly'],
    suitableForDisplay: true,
    suitableForBody: true,
    sortOrder: 45,
  },
  {
    slug: 'sacramento',
    family: 'Sacramento',
    category: 'handwriting',
    tags: ['Script', 'Elegant', 'Delicate'],
    suitableForDisplay: true,
    suitableForBody: false,
    sortOrder: 46,
  },
  {
    slug: 'satisfy',
    family: 'Satisfy',
    category: 'handwriting',
    tags: ['Script', 'Casual', 'Warm'],
    suitableForDisplay: true,
    suitableForBody: false,
    sortOrder: 47,
  },
  {
    slug: 'secular-one',
    family: 'Secular One',
    category: 'sans-serif',
    tags: ['Bold', 'Geometric', 'Strong'],
    suitableForDisplay: true,
    suitableForBody: false,
    sortOrder: 48,
  },
  {
    slug: 'shadows-into-light',
    family: 'Shadows Into Light',
    category: 'handwriting',
    tags: ['Handwritten', 'Casual', 'Personal'],
    suitableForDisplay: true,
    suitableForBody: false,
    sortOrder: 49,
  },
  {
    slug: 'source-sans-3',
    family: 'Source Sans 3',
    category: 'sans-serif',
    tags: ['Clean', 'Readable', 'Professional'],
    suitableForDisplay: false,
    suitableForBody: true,
    sortOrder: 50,
  },

  // Body-focused + more versatile
  {
    slug: 'source-serif-4',
    family: 'Source Serif 4',
    category: 'serif',
    tags: ['Readable', 'Editorial', 'Professional'],
    suitableForDisplay: false,
    suitableForBody: true,
    sortOrder: 51,
  },
  {
    slug: 'spectral',
    family: 'Spectral',
    category: 'serif',
    tags: ['Literary', 'Readable', 'Refined'],
    suitableForDisplay: true,
    suitableForBody: true,
    sortOrder: 52,
  },
  {
    slug: 'syne',
    family: 'Syne',
    category: 'sans-serif',
    tags: ['Bold', 'Contemporary', 'Brand'],
    suitableForDisplay: true,
    suitableForBody: false,
    sortOrder: 53,
  },
  {
    slug: 'titillium-web',
    family: 'Titillium Web',
    category: 'sans-serif',
    tags: ['Tech', 'Clean', 'Modern'],
    suitableForDisplay: true,
    suitableForBody: true,
    sortOrder: 54,
  },
  {
    slug: 'ubuntu',
    family: 'Ubuntu',
    category: 'sans-serif',
    tags: ['Friendly', 'Humanist', 'Clear'],
    suitableForDisplay: true,
    suitableForBody: true,
    sortOrder: 55,
  },
  {
    slug: 'work-sans',
    family: 'Work Sans',
    category: 'sans-serif',
    tags: ['Clean', 'Readable', 'Modern'],
    suitableForDisplay: true,
    suitableForBody: true,
    sortOrder: 56,
  },
  {
    slug: 'yanone-kaffeesatz',
    family: 'Yanone Kaffeesatz',
    category: 'sans-serif',
    tags: ['Condensed', 'Headline', 'Warm'],
    suitableForDisplay: true,
    suitableForBody: false,
    sortOrder: 57,
  },
  {
    slug: 'zilla-slab',
    family: 'Zilla Slab',
    category: 'serif',
    tags: ['Slab', 'Friendly', 'Modern'],
    suitableForDisplay: true,
    suitableForBody: true,
    sortOrder: 58,
  },
  {
    slug: 'alegreya',
    family: 'Alegreya',
    category: 'serif',
    tags: ['Literary', 'Readable', 'Warm'],
    suitableForDisplay: true,
    suitableForBody: true,
    sortOrder: 59,
  },
  {
    slug: 'alegreya-sans',
    family: 'Alegreya Sans',
    category: 'sans-serif',
    tags: ['Humanist', 'Readable', 'Warm'],
    suitableForDisplay: false,
    suitableForBody: true,
    sortOrder: 60,
  },
  {
    slug: 'arvo',
    family: 'Arvo',
    category: 'serif',
    tags: ['Slab', 'Sturdy', 'Clear'],
    suitableForDisplay: true,
    suitableForBody: true,
    sortOrder: 61,
  },
  {
    slug: 'asap',
    family: 'Asap',
    category: 'sans-serif',
    tags: ['Compact', 'Readable', 'Practical'],
    suitableForDisplay: false,
    suitableForBody: true,
    sortOrder: 62,
  },
  {
    slug: 'assistant',
    family: 'Assistant',
    category: 'sans-serif',
    tags: ['Clean', 'Readable', 'Neutral'],
    suitableForDisplay: false,
    suitableForBody: true,
    sortOrder: 63,
  },
  {
    slug: 'cairo',
    family: 'Cairo',
    category: 'sans-serif',
    tags: ['Modern', 'Geometric', 'Clear'],
    suitableForDisplay: true,
    suitableForBody: true,
    sortOrder: 64,
  },
  {
    slug: 'cardo',
    family: 'Cardo',
    category: 'serif',
    tags: ['Classical', 'Literary', 'Readable'],
    suitableForDisplay: false,
    suitableForBody: true,
    sortOrder: 65,
  },
  {
    slug: 'catamaran',
    family: 'Catamaran',
    category: 'sans-serif',
    tags: ['Friendly', 'Readable', 'Soft'],
    suitableForDisplay: false,
    suitableForBody: true,
    sortOrder: 66,
  },
  {
    slug: 'crimson-text',
    family: 'Crimson Text',
    category: 'serif',
    tags: ['Literary', 'Classic', 'Readable'],
    suitableForDisplay: false,
    suitableForBody: true,
    sortOrder: 67,
  },
  {
    slug: 'domine',
    family: 'Domine',
    category: 'serif',
    tags: ['Editorial', 'Strong', 'Readable'],
    suitableForDisplay: true,
    suitableForBody: true,
    sortOrder: 68,
  },
  {
    slug: 'eb-garamond',
    family: 'EB Garamond',
    category: 'serif',
    tags: ['Classic', 'Literary', 'Elegant'],
    suitableForDisplay: true,
    suitableForBody: true,
    sortOrder: 69,
  },
  {
    slug: 'figtree',
    family: 'Figtree',
    category: 'sans-serif',
    tags: ['Modern', 'Friendly', 'Clean'],
    suitableForDisplay: true,
    suitableForBody: true,
    sortOrder: 70,
  },
  {
    slug: 'fira-sans',
    family: 'Fira Sans',
    category: 'sans-serif',
    tags: ['Technical', 'Readable', 'Clear'],
    suitableForDisplay: false,
    suitableForBody: true,
    sortOrder: 71,
  },
  {
    slug: 'frank-ruhl-libre',
    family: 'Frank Ruhl Libre',
    category: 'serif',
    tags: ['Editorial', 'Warm', 'Readable'],
    suitableForDisplay: true,
    suitableForBody: true,
    sortOrder: 72,
  },
  {
    slug: 'heebo',
    family: 'Heebo',
    category: 'sans-serif',
    tags: ['Clean', 'Modern', 'Readable'],
    suitableForDisplay: false,
    suitableForBody: true,
    sortOrder: 73,
  },
  {
    slug: 'hind',
    family: 'Hind',
    category: 'sans-serif',
    tags: ['Humanist', 'Readable', 'Clear'],
    suitableForDisplay: false,
    suitableForBody: true,
    sortOrder: 74,
  },
  {
    slug: 'inconsolata',
    family: 'Inconsolata',
    category: 'monospace',
    tags: ['Code', 'Technical', 'Mono'],
    suitableForDisplay: false,
    suitableForBody: true,
    sortOrder: 75,
  },
  {
    slug: 'karla',
    family: 'Karla',
    category: 'sans-serif',
    tags: ['Friendly', 'Readable', 'Warm'],
    suitableForDisplay: false,
    suitableForBody: true,
    sortOrder: 76,
  },
  {
    slug: 'libre-franklin',
    family: 'Libre Franklin',
    category: 'sans-serif',
    tags: ['Neutral', 'Readable', 'Professional'],
    suitableForDisplay: false,
    suitableForBody: true,
    sortOrder: 77,
  },
  {
    slug: 'lora',
    family: 'Lora',
    category: 'serif',
    tags: ['Editorial', 'Warm', 'Readable'],
    suitableForDisplay: true,
    suitableForBody: true,
    sortOrder: 78,
  },
  {
    slug: 'mulish',
    family: 'Mulish',
    category: 'sans-serif',
    tags: ['Clean', 'Modern', 'Readable'],
    suitableForDisplay: false,
    suitableForBody: true,
    sortOrder: 79,
  },
  {
    slug: 'noto-sans',
    family: 'Noto Sans',
    category: 'sans-serif',
    tags: ['Neutral', 'Readable', 'Universal'],
    suitableForDisplay: false,
    suitableForBody: true,
    sortOrder: 80,
  },
  {
    slug: 'noto-serif',
    family: 'Noto Serif',
    category: 'serif',
    tags: ['Neutral', 'Readable', 'Universal'],
    suitableForDisplay: false,
    suitableForBody: true,
    sortOrder: 81,
  },
  {
    slug: 'nunito-sans',
    family: 'Nunito Sans',
    category: 'sans-serif',
    tags: ['Rounded', 'Readable', 'Friendly'],
    suitableForDisplay: false,
    suitableForBody: true,
    sortOrder: 82,
  },
  {
    slug: 'open-sans',
    family: 'Open Sans',
    category: 'sans-serif',
    tags: ['Friendly', 'Readable', 'Familiar'],
    suitableForDisplay: false,
    suitableForBody: true,
    sortOrder: 83,
  },
  {
    slug: 'overpass',
    family: 'Overpass',
    category: 'sans-serif',
    tags: ['Technical', 'Clean', 'Readable'],
    suitableForDisplay: false,
    suitableForBody: true,
    sortOrder: 84,
  },
  {
    slug: 'prompt',
    family: 'Prompt',
    category: 'sans-serif',
    tags: ['Modern', 'Geometric', 'Clear'],
    suitableForDisplay: true,
    suitableForBody: true,
    sortOrder: 85,
  },
  {
    slug: 'public-sans',
    family: 'Public Sans',
    category: 'sans-serif',
    tags: ['Neutral', 'Readable', 'Civic'],
    suitableForDisplay: false,
    suitableForBody: true,
    sortOrder: 86,
  },
  {
    slug: 'red-hat-display',
    family: 'Red Hat Display',
    category: 'sans-serif',
    tags: ['Bold', 'Modern', 'Brand'],
    suitableForDisplay: true,
    suitableForBody: false,
    sortOrder: 87,
  },
  {
    slug: 'red-hat-text',
    family: 'Red Hat Text',
    category: 'sans-serif',
    tags: ['Readable', 'Modern', 'Clear'],
    suitableForDisplay: false,
    suitableForBody: true,
    sortOrder: 88,
  },
  {
    slug: 'roboto-slab',
    family: 'Roboto Slab',
    category: 'serif',
    tags: ['Slab', 'Readable', 'Sturdy'],
    suitableForDisplay: true,
    suitableForBody: true,
    sortOrder: 89,
  },
  {
    slug: 'schibsted-grotesk',
    family: 'Schibsted Grotesk',
    category: 'sans-serif',
    tags: ['Editorial', 'Modern', 'Clean'],
    suitableForDisplay: true,
    suitableForBody: true,
    sortOrder: 90,
  },
  {
    slug: 'sora',
    family: 'Sora',
    category: 'sans-serif',
    tags: ['Modern', 'Geometric', 'Tech'],
    suitableForDisplay: true,
    suitableForBody: true,
    sortOrder: 91,
  },
  {
    slug: 'space-mono',
    family: 'Space Mono',
    category: 'monospace',
    tags: ['Mono', 'Tech', 'Distinct'],
    suitableForDisplay: true,
    suitableForBody: false,
    sortOrder: 92,
  },
  {
    slug: 'spline-sans',
    family: 'Spline Sans',
    category: 'sans-serif',
    tags: ['Modern', 'Geometric', 'Brand'],
    suitableForDisplay: true,
    suitableForBody: true,
    sortOrder: 93,
  },
  {
    slug: 'teko',
    family: 'Teko',
    category: 'sans-serif',
    tags: ['Condensed', 'Bold', 'Headline'],
    suitableForDisplay: true,
    suitableForBody: false,
    sortOrder: 94,
  },
  {
    slug: 'urbanist',
    family: 'Urbanist',
    category: 'sans-serif',
    tags: ['Modern', 'Geometric', 'Clean'],
    suitableForDisplay: true,
    suitableForBody: true,
    sortOrder: 95,
  },
  {
    slug: 'vollkorn',
    family: 'Vollkorn',
    category: 'serif',
    tags: ['Classic', 'Readable', 'Warm'],
    suitableForDisplay: false,
    suitableForBody: true,
    sortOrder: 96,
  },
  {
    slug: 'lexend',
    family: 'Lexend',
    category: 'sans-serif',
    tags: ['Readable', 'Accessible', 'Clear'],
    suitableForDisplay: false,
    suitableForBody: true,
    sortOrder: 97,
  },
  {
    slug: 'plus-jakarta-sans',
    family: 'Plus Jakarta Sans',
    category: 'sans-serif',
    tags: ['Modern', 'Friendly', 'Brand'],
    suitableForDisplay: true,
    suitableForBody: true,
    sortOrder: 98,
  },
  {
    slug: 'instrument-sans',
    family: 'Instrument Sans',
    category: 'sans-serif',
    tags: ['Modern', 'Editorial', 'Clean'],
    suitableForDisplay: true,
    suitableForBody: true,
    sortOrder: 99,
  },
  {
    slug: 'fraunces',
    family: 'Fraunces',
    category: 'serif',
    tags: ['Expressive', 'Editorial', 'Distinct'],
    suitableForDisplay: true,
    suitableForBody: false,
    sortOrder: 100,
  },
];
